### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION yii2advanced.date_part does not exist

### ISSUE THREAD

**Issue by erycamel** [sangkil/biz3-distro#1]
Database Exception – yii\db\Exception

SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION yii2advanced.date_part does not exist
The SQL being executed was: SELECT COUNT(*) FROM (SELECT `branch_id`, `branch`.`name`, sum(value) as value FROM `sales` LEFT JOIN `branch` ON `sales`.`branch_id` = `branch`.`id` WHERE (`branch_id`=-1) AND (date_part('month',date)=7) GROUP BY `branch_id`, `branch`.`name`) `c`
Error Info: Array
(
    [0] => 42000
    [1] => 1305
    [2] => FUNCTION yii2advanced.date_part does not exist
)
↵
Caused by: PDOException

SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION yii2advanced.date_part does not exist

in D:\xampp\htdocs\biz3-distro\vendor\yiisoft\yii2\db\Command.php at line 900

**Comment by mdmunir** [comment]
This app developed under postgresql. So, some code may only work with postgres. Any idea to make it dbms independent?
